version: 0.2

env:
  parameter-store:
    ENV_FILE: "DEMO_REACT_APP_API"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $ENV_FILE > ./front-end/.env
      - docker build -t $AWS_ECR_REPO:demo-athena -f ./front-end/docker/react/Dockerfile ./front-end
      - docker build -t $AWS_ECR_REPO:demo-athena-nginx -f ./front-end/docker/nginx/Dockerfile ./front-end

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ECR_REPO:demo-athena
      - docker push $AWS_ECR_REPO:demo-athena-nginx
  
artifacts:
  files:
    - 'appspec.yml'
    - 'scripts/*'
    - 'docker-compose-demo.deploy.yml'
  name: Demo-Athena-artifact
