version: "3.8"

services:
  demo-athena-nginx:
    image: "192479299400.dkr.ecr.ap-southeast-2.amazonaws.com/athena:demo-athena-nginx"
    container_name: "demo-athena-nginx"
    restart: always
    ports:
      - 80:80
    volumes:
      - build:/var/www/build
    depends_on:
      - front-end
    networks:
      - athena

  demo-athena:
    image: "192479299400.dkr.ecr.ap-southeast-2.amazonaws.com/athena:demo-athena"
    container_name: "demo-athena"
    volumes:
      - build:/app/build
    environment:
      - NODE_ENV=development
    networks:
      - athena

volumes:
  build:

networks:
  athena:
    driver: bridge